gateway-base-url: https://ink3.shop/gateway
toss:
  url:
    success: https://ink3.shop/payments/success
    fail: https://ink3.shop/payments/fail
    success-guest: https://ink3.shop/guest-payment/success
    fail-guest: https://ink3.shop/guest-payment/fail
feign:
  url:
    gateway: http://127.0.0.1:10250
    auth: http://127.0.0.1:10250/auth
    shop: http://127.0.0.1:10250/shop
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
